JeffersonLab/SBS-offline

SBSHCal.cxx
SBSHCal.h

- Pushing changes from testlab computer relating to the pulser system on HCal

HCal Pulser decoding

---

SBSBBShower.cxx
SBSBBShower.h
SBSBBTotalShower.cxx
SBSCalorimeter.cxx
SBSCalorimeter.h

Update SBSCalorimeter.cxx and h
SBSCalorimeter.h add Bool_t Incluster, x and y position to SBSBlockSet
SBSCalorimeter::MakeGoodBlocks
Changed so that it only check if ADC good_hit
to add to fGoodBlocks and fBlockSet
Modify ReadDatabase so that the block position
can be read in as parameter xpos and ypos vector
with vector size = number of elements.
Update SBSBBShower,SBSBBTotalShower
Changes need for PreShower/Shower cluster matching
Needed new method for making PreShower clusters
SBSBBShower
a) Add method MakeCluster for starting cluster
b) Add method AddToCluster for adding blocks to cluster
c) Add method MakeMainCluster for making fMainclus
and calculates fNclus
SBSBBTotalShower
a) USe fMaxDx and fMaxDy for matching Shower/PreShower clusters
b) Write code for match PreShower blocks to …

Cal dev aug20

---

SBSCalorimeter.cxx
SBSGenericDetector.cxx

***********
Update Waveform a_p and a_mult in SBSGenericDetector::CoarseProcess
For the waveform mode:
When filling a_p change to divide val by the gain factor.
Set a_mult = 1 if the time is greater than zero.
*********
Modify SBSCalorimeter to read-in trigtoFADCratio
Modified SBSCalorimeter::ReadDatabase to read in the parameters
trigtoFADCratio which is vector fo the ratio of the amplitude
at the Trigger sum FI/FO output to the FADC amplitude.
If trigtoFADCratio is set then the adc gain for the  SBS element
is change to gain*trigtoFADCratio

Update SBSGenericDetector and SBSCalorimeter

---

SBSTimingHodoscope.cxx
SBSTimingHodoscope.h

Removed SBSTimingHodoscope FindGoodHit function in SBSTimingHodoscope.cxx and SBSTimingHodoscope.h

Removed SBSTimingHodoscope FindGoodHit

---

SBSBBShower.cxx
SBSCalorimeter.cxx
SBSCalorimeter.h
SBSCalorimeterCluster.cxx
SBSCalorimeterCluster.h
SBSElement.cxx
SBSElement.h

SBSCalorimeter.h
1) Add protected variable fTDCtime with Get and Set methods
SBSElement.h
1) Add protected variable fTDCtime with Get and Set methods
SBSCalorimeter.cxx
1) Default fTDCtime = 0 when creating cluster
2) Fill fTDCtime with block TDCtime of the block with the largest energy
SBSElement.cxx
1) In construction, fTDCtime = kBig
2) In clear event set  fTDCtime = kBig
SBSCalorimeter.h
1) Add tdctime to the SBSCalBlocks structure
2) Add method GetTDCtime
SBSCalorimeter.cxx
1) Add tree variables tdctimeblk, clus_blk.tdctime,clus.tdctime
2) In MakeGoodBlocks, set the block TDC time.
If no TDC hit then default = -1000
3) Fill the tree output structures with TDC time
SBSBBShower
1) Fill TDc time in tree output structure

Updated SBSCalorimeterCluster to have TDC time

---

SBSCalorimeter.cxx
SBSCalorimeter.h

- The DB parameter is **emin_clSeed**.
- Ex: For BBShower detector use: bb.sh.emin_clSeed = <desired_eng> # GeV

Added feature to be able to cut on minimum cluster seed energy.

---

SBSData.cxx
SBSData.h
SBSDecodeF1TDCModule.cxx
SBSGenericDetector.cxx

DB parameter: <genericdetector>.adc.timeoffset 
NOTE: User should put the value in ns. The given offset will be **added** to the adc time at every event.

Adc time-offset set parameter added 

---

SBSGEMModule.cxx
SBSGEMModule.h
SBSGEMSpectrometerTracker.cxx
SBSGEMTrackerBase.cxx
SBSGEMTrackerBase.h

Added negative strip clustering and tracking checks. Only used if a flag do_neg_signal_study is on in the db_bb.gem.dat is on.

Add GEM negative signal analysis functionality

---

SBSGEMModule.cxx
SBSGEMModule.h
SBSGEMSpectrometerTracker.cxx
SBSGEMTrackerBase.cxx
SBSGEMTrackerBase.h

The DB loading still works, but is overwritten by the new file, if one exists

Added GEM CM DB file parsing

---

SBSGEMModule.cxx
SBSGEMModule.h

Added some quality of life decoding info to the GEM decoding. Now the CODA configuration is read automatically instead of written by hand in the DB. However if a particular run cannot find the information in the EVIO file, then it will default back to whatever is in the DB.

changed aesthetics of GEM common mode plots

---

SBSGEMModule.cxx

Earlier I was uding GetNConfig but this was causing errors with some evio files. I found it was guaranteed to work if I switched to using GetDAQInfo to tell if the GEM DAQ information was found in the evio file

Fixed GEM DAQ decoding

---

SBSScalerHelicityReader.cxx

When there are inconsistencies between the two arms or between the FADC reported signals and what is reconstructed from scaler stream, the "true helicity" is set to zero and the error code field is filled to indicate the issue.

Addiing additional consistency checks between the SBS and LHRS helicity scaler and FADC bits.

---

SBSGEMModule.cxx

Changed ranges on plots for aesthetics and removed CM_OUT_OF_RANGE events from CM diagnostic plots

Modified CM plots

---

SBSGenericDetector.cxx

seeing rollover peak ~7000 in hcal tdc, which is fixed by replacing two if with if..else if.

bug fixed for f1tdc rollover

---

SBSGenericDetector.cxx
SBSManager.cxx
SBSManager.h
cmake/modules/FindPodd.cmake

Fixes incorrect crate map initialization due to wrong time stamp argument.

SBSManager cratemap time fix

---

SBSSimDecoder.cxx
SBSSimFile.cxx

Edited:
SBSSimDecoder.cxx
charge exchange front gem: sbs.gemCeF;
charge exchange front gem: sbs.gemCeR;
side gem: sbs.gemPR;
side hodoscope: sbs.hodoPR;

Changed the name of GEN-RP detectors in MC

---

CMakeLists.txt
SBSCDet.cxx
SBSCDet.h
SBSGEPEArm.cxx
SBSGEPEArm.h
SBSSimDecoder.cxx
sbs_LinkDef.h

Added a class for the GEP electron are, called SBSGEPEArm, copied from SBSEArm, with most of the code commented out.
Changed inheritance for CDet from THaNonTrackingDetector to SBSGenericDetector, and commented out most of the code.

GEP electron arm skeleton code

---

SBSGenericDetector.cxx
SBSGenericDetector.h

1. *.adcxpos => x-positions (m) for block in data vectors
2. *.adcypos => y-positions (m) for block in data vectors

Added the following new output variables to SBSGenericDetector class:

---

SBSVTP.cxx
VTPModule.cxx
VTPModule.h

The HCAL VTp detector ID was changed to 13.
The HCAL VTP data structure was changed so it is updated.

[MKJ] Modified VTPModule.cxx and header

---

VETROCcdet.cxx

Decoder updates
