MPDModule.cxx, MPDModule.h, SBSBBShower.cxx, SBSCDet.cxx, SBSCalorimeter.cxx, SBSDecodeF1TDCModule.cxx, SBSDecodeF1TDCModule.h, SBSECal.cxx, SBSGEMPlane.cxx, SBSGRINCH.cxx, SBSGRINCH_ClusterList.h, SBSHCal.cxx, SBSScintPlane.cxx, SBSSimADC.cxx, SBSSimADC.h, SBSSimTDC.cxx, SBSSimTDC.h, SBSTimingHodoscope.cxx
Adjust the codebase to work with Podd 1.7.0-rc2.
In a few places, Int_t parameters and return values in the decoder API have been changed to UInt_t. I have propagated these changes beyond the API calls to also change the type of some local variables accordingly. Even though it might look invasive, these are essentially trivial changes.
I also took the opportunity to fix a number of compilation warnings about suspicious code. I left "unused variable" warnings alone.
If you merge this pull request, you will also need to update to the latest Podd release on the master branch. The relevant tag is Release-170-rc2.
=> Updates for Podd 1.7 rc2

SBSGenericDetector.cxx
1) ReadDatabase: Fixed bug that the fRefChanLo and fRefChanHi
were set incorrectly in the low channel number in the
detmap was non-zero.
2) FindGoodHit: If fModeADc is kWaveform use the ADC raw time
to determine if a pulse was found. Previously was using
the calibrated time.
=> Updated SBSGenericDetector fix ref time bug and modified FindGoodHit

SBSDecodeF1TDCModule.cxx
LoadSlot was not using the trigger time correctly
when using it to determine the rollover.
This use of the trigger time to determine rollover
relies on the trigger time being after the detector times
and not closer than 25ns.
=> Fix problem in SBSDecodeF1TDCModule::LoadSlot

SBSData.cxx
The pedestal for the FADC mode 7 does not need to be divided by 4.
=> Modify SBSData ADC::Process

SBSHCal.cxx, SBSHCalLEDModule.cxx, SBSHCalLEDModule.h
Changed the SBSHCalLED.cxx and .h files to account for previous analyzer change switching Int_t to UInt_t. This change was made to the return values of the LoadSlot function and the arguments passed to this function. This change will enable the decoding of HCal LED info again.
=> Skbarcus dev

SBSGenericDetector.cxx
When filling the a_p for the tree need to do it different
for the FADC mode 7 (kADC) compared to kADCSimple
=> Modify SBSGenericDetector::CoarseProcess

SBSBBTotalShower.cxx, SBSCalorimeter.cxx
SSBBBTotalShower
Matching between Shower and PreShower
uses cuts on the X and Y position differences between
SHower cluster and Preshower blocks.
The parameters are MaxDx and MaxDy in meters
SBSCalorimeter
Determining blocks to include in the cluster uses a radius
cut between the block and the cluster
The parameter RMax_dis in meters
=> Make cluster matching cuts DB parameters

SBSCalorimeter.cxx, SBSData.cxx, SBSData.h, SBSGenericDetector.cxx, SBSGenericDetector.h
SBSData.cxx
1) Modify ADC and Waveform Process so that amplitude val uses acal as the amplitude gain factor.
SBSData.h
1) Add variable trigcal ( Trig amp/ Fadc amp ratio)
2) Add method GetTrigCal and SetTrigCal.
3) Add method GetAmpCal to the Waveform
SBSGenericDetector.h
1) Add variable a_amp_c to SBSGenericOutputData
2) Add variables a_amptrig_p and a_amptrig_c to SBSGenericOutputData
SBSGenericDetector.cxx
1) Add parameters refadc_AmpToIntRatio and adc_AmpToIntRatio
By default there are set to 1.
2) After creating the SBSElement set the Amplitude cal to
AmpToIntRatio*gain and set the trigger ratio to 1.
The trigger ratio is read in in the SBSCalorimeter readdatabase.
3) In DefineVariables method, add tree variables a_amp_c. a_amptrig_p,
a_amptrig_c
4) In CoarseProcess method, fill the …
=> Modify SBSGenericDetector, SBSCalorimeter, SBSData

SBSCalorimeter.cxx
Was filling fMainclusblk.e twice instead of filling
fMainclusblk.e_c
=> Fix typo in SBSCalorimeter::FineProcess

VETROC.cxx
The Decoder was filling the wrong variable with the slot number.
=> Fix VETROC.cxx

SBSData.cxx, SBSTimingHodoscope.cxx
Fixes a few small memory leaks and bad array accesses found by valgrind memcheck.
Someone should take a look at SBSTimingHodoscope::DoClustering and decide what to do in the degenerate case where fGoodBarIDsTDC.size() == 1. Currently, the result is that no clusters are generated, i.e. fClusters is empty on exit. This is probably not quite correct, but I didn't want to make assumptions on behalf of the detector experts.
=> Valgrind fixes

SBSBigBite.cxx, SBSBigBite.h
- Turn PID calculations on in the first place, i.e. tell the analyzer actually to call CalcPID() from THaSpectrometer::Reconstruct()
- Use the PIDinfo class in the way it was intended. It is not necessary to allocate a new object for every track. This is already done in THaSpectrometer::ListInit, using the particle types defined in DefinePidParticles()
=> Fixup PIDinfo handling

CMakeLists.txt
By pure accident, I discovered that the default build type was set to "Debug". Someone had later hardcoded "RelWithDebInfo" elsewhere in CMakeLists.txt, which was then removed because hardcoding a variable like this is a bad idea, thus reverting to this default, which is arguably no longer suitable since we're using this repo for production now.
=> CMake: Make RelWithDebInfo the default build type

SBSGenericDetector.cxx, SBSGenericDetector.h
Need to make changes to time order the TDC hit data, since
from the VETROC the hits are not in time order.
Added structure TDCHits to SBSGenericDetector.h
In DecodeTDC :
Fill vector of TDCHits with edge and rawtime of hits
Sort TDCHits vector in ascending order of time
Use TDCHits vector when processing the TDC hits.
=> Changes to SBSGenericDetector::DecodeTDC

SBSGEMModule.cxx, SBSGEMModule.h
Map lookups quickly get expensive when done in inner loops ...
This basically trivial change gives a small (5%-ish) speedup in the GEM module decoding.
=> Make APVMAP a std::array to speed up GetStripNumber

LHRSScalerEvtHandler.cxx, LHRSScalerEvtHandler.h, SBSScalerEvtHandler.cxx, SBSScalerEvtHandler.h
Re-implemented fixes to the LHRSScalerEvtHandler to properly decode inserted scaler events.  Verified the fix with a replayed run to show BCM counts, rates, and currents match for LHRS and SBS scaler tree variables.
=> Fixes to LHRSScalerEvtHandler

SBSBBShower.cxx, SBSBigBite.cxx, SBSCalorimeter.cxx, SBSCalorimeter.h, SBSCalorimeterCluster.cxx, SBSCalorimeterCluster.h, SBSElement.cxx, SBSElement.h
1. Disabled *.e_c and *.eblk_c variables. Since they were just mere copies of *.e and *.eblk respectively.
2. Added *.againblk, *.clus.again, *.clus_blk.again variables. They contain ADC gain coefficients (GeV/pC) for the blocks in cluster. This will be hugely useful for calorimeter calibration.
=> List of changes:

SBSScalerHelicity.cxx, SBSScalerHelicity.h, SBSScalerHelicityReader.cxx, SBSScalerHelicityReader.h
The true helicity, helicity event and pattern counters, and state of the T_settle signal can now be made available in the standard "T" tree with an appropriate odef file.  There are also some other diagnostic words that can be put in the tree if desired.
An independent "TShel" tree is also created, which is filled for each helicity scaler reading, and scaler asymmetries can be calculated on a pattern-by-pattern basis within this tree.  At the moment, calibrations to turn the raw scaler counts to beam current are not included in the code, but that would be the next step.  At the moment the results are not easily interpretable by the casual viewer, as it is still heavy on diagnostic information.
The current version of the SBSScalerHelicity and SBSScalerHelicityReader classes still contain …
=> Feature charge asymmetry

SBSScalerHelicityReader.cxx
The first fix is for a typo in the test that the FADC helicity bit agrees with the predicted helicity bit; this can cause occasional spurious "zero helicity" events, but not generally a large number of them at a time.
The second fix is more significant:  the helicity scalers in the LHRS and SBS crates begin accumulating scaler events at the GO transition, and there is a test that the number of scaler events is consistent between the two arms.  However, it is possible for one crate to get enabled just early enough to be able to count an extra event.  This had then caused all events to fail this test for the rest of the run.
The fix is to allow an offset between the two event counters.  If they do not agree with consideration of the offset, that physics event is marked as having a bad …
=> Changes in the Helicity Scaler decoding to reduce "zero helicity" events

SBSSimDecoder.cxx, SBSSimDecoder.h, gmn_tree_digitized.h
Added a couple of new output variables "simc.veE" and "simc.vetheta" to store scattered e- energy and angle at the vertex, respectively. This will enable us to calculate "true" vertex.
=> Updates related to SIMC generator

SBSScalerHelicity.cxx, SBSScalerHelicity.h
**There is no change to the behavior of the "scalhel.hel" variable in the physics "T" tree.  That remains the best way to tag the physics events with the helicity state.**
When we wrote SBSScalerHelicity originally, it was derived from previous scaler helicity analysis classes, and we had not bothered to entirely cleanup functions, data members, and "TShel" TTree output variables which had become superseded.
That made it kind of difficult to remember how to actually plot the (raw) charge asymmetry or otherwise manipulate the "TShel" TTree.
I have now removed unused functions and data members from the class, and substantially cleaned up the branches in the "TShel" TTree. To plot the raw asymmetry for the second scaler channel you would do:
TShel->Draw("Lhel.Diff.Ch1/Lhel.Yield.Ch1", …
=> Major cleanup of unused code and TTree outputs from SBSScalerHelicity

SBSCalorimeter.cxx, SBSCalorimeter.h, SBSCalorimeterCluster.cxx, SBSCalorimeterCluster.h, SBSElement.cxx, SBSElement.h
Fixed the mistake from the previous PR
Implemented HCal TDC timewalk corrections based on tof calibration work over past several months. This does not include internal alignemnt or rf corrections yet as have been done for the hodoscope, but is still an improvement for gen pass2 replays, for now.
=> HCal TDC Timewalk machinery
